#Yakovlev
version: '3.1'

services:
#http://localhost:8081/items/5?q=somequery
  fastapi:
    build: ./
    ports:
      - 8081:80


  db:
    container_name: db
    image: postgres:alpine3.17
    restart: always
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080